window.INTEGRATED_APPS = [
  {
    id: "renrakucho",
    title: "連絡帳作成",
    description: "小学校の連絡帳用紙に合わせて、薄い見本文字を作成して印刷できます。",
    category: "学校",
    tags: ["連絡帳", "印刷", "PDF"],
    href: "apps/renrakucho/index.html",
    actionLabel: "連絡帳を作る",
    status: "ready",
    accent: "#0072bc",
  },
  {
    id: "kanji-print",
    title: "漢字なぞりプリント",
    description: "文章から漢字練習用のなぞりプリントを作成して印刷できます。",
    category: "教材",
    tags: ["漢字", "なぞり", "印刷"],
    href: "apps/kanji-print/index.html",
    actionLabel: "プリントを作る",
    status: "ready",
    accent: "#0f7b5f",
  },
  {
    id: "math-print-grade1",
    title: "1年生 計算プリント",
    description: "小学1年生向けのたし算・ひき算プリントを自動作成して印刷できます。",
    category: "教材",
    tags: ["計算", "1年生", "印刷"],
    href: "apps/math-print-grade1/index.html",
    actionLabel: "計算プリントを作る",
    status: "ready",
    accent: "#b45f06",
  },
  {
    id: "math-print-grade2",
    title: "2年生 計算プリント",
    description: "小学2年生向けの2けた計算と九九のプリントを自動作成して印刷できます。",
    category: "教材",
    tags: ["計算", "2年生", "九九", "筆算", "印刷"],
    href: "apps/math-print-grade2/index.html",
    actionLabel: "2年生プリントを作る",
    status: "ready",
    accent: "#2f7d6d",
  },
];
