window.INTEGRATED_APPS = [
  {
    id: "renrakucho",
    title: "連絡帳作成",
    description: "小学校の連絡帳用紙に合わせて、薄い見本文字を作成して印刷できます。",
    category: "学校",
    tags: ["連絡帳", "印刷", "PDF"],
    href: "apps/renrakucho/index.html",
    actionLabel: "連絡帳を作る",
    status: "ready",
    accent: "#0072bc",
  },
  {
    id: "kanji-print",
    title: "漢字なぞりプリント",
    description: "文章から漢字練習用のなぞりプリントを作成して印刷できます。",
    category: "教材",
    tags: ["漢字", "なぞり", "印刷"],
    href: "apps/kanji-print/index.html",
    actionLabel: "プリントを作る",
    status: "ready",
    accent: "#0f7b5f",
  },
  {
    id: "math-print-grade1",
    title: "1年生 計算プリント",
    description: "小学1年生向けのたし算・ひき算プリントを自動作成して印刷できます。",
    category: "教材",
    tags: ["計算", "1年生", "印刷"],
    href: "apps/math-print-grade1/index.html",
    actionLabel: "計算プリントを作る",
    status: "ready",
    accent: "#b45f06",
  },
  {
    id: "math-print-grade2",
    title: "2年生 計算プリント",
    description: "小学2年生向けの2けた計算と九九のプリントを自動作成して印刷できます。",
    category: "教材",
    tags: ["計算", "2年生", "九九", "筆算", "印刷"],
    href: "apps/math-print-grade2/index.html",
    actionLabel: "2年生プリントを作る",
    status: "ready",
    accent: "#2f7d6d",
  },
  {
    id: "time-print-grade2",
    title: "2年生 時刻・時間",
    description: "時計を読む、針を描く、何分後・何分前を考えるプリントを作成できます。",
    category: "教材",
    tags: ["算数", "2年生", "時刻", "時間", "印刷"],
    href: "apps/time-print-grade2/index.html",
    actionLabel: "時刻プリントを作る",
    status: "ready",
    accent: "#2563eb",
  },
  {
    id: "length-print-grade2",
    title: "2年生 長さ",
    description: "cm、mm、mの読み取りや単位換算、長さ比べのプリントを作成できます。",
    category: "教材",
    tags: ["算数", "2年生", "長さ", "ものさし", "印刷"],
    href: "apps/length-print-grade2/index.html",
    actionLabel: "長さプリントを作る",
    status: "ready",
    accent: "#0f766e",
  },
  {
    id: "capacity-print-grade2",
    title: "2年生 水のかさ",
    description: "L、dL、mLの単位変換プリントを作成できます。",
    category: "教材",
    tags: ["算数", "2年生", "水のかさ", "単位変換", "印刷"],
    href: "apps/capacity-print-grade2/index.html",
    actionLabel: "単位変換プリントを作る",
    status: "ready",
    accent: "#0284c7",
  },
  {
    id: "shape-print-grade2",
    title: "2年生 図形",
    description: "三角形、四角形、長方形、正方形、直角三角形の名前を書くプリントを作成できます。",
    category: "教材",
    tags: ["算数", "2年生", "図形", "名前", "印刷"],
    href: "apps/shape-print-grade2/index.html",
    actionLabel: "名前プリントを作る",
    status: "ready",
    accent: "#7c3aed",
  },
  {
    id: "table-graph-print-grade2",
    title: "2年生 表とグラフ",
    description: "簡単な表や棒グラフを読み取るプリントを作成できます。",
    category: "教材",
    tags: ["算数", "2年生", "表", "グラフ", "印刷"],
    href: "apps/table-graph-print-grade2/index.html",
    actionLabel: "表とグラフを作る",
    status: "ready",
    accent: "#c2410c",
  },
];

