const els={sourceText:document.querySelector('#sourceText'),studentName:document.querySelector('#studentName'),worksheetDate:document.querySelector('#worksheetDate'),cols:document.querySelector('#cols'),rows:document.querySelector('#rows'),fontSize:document.querySelector('#fontSize'),smallFontSize:document.querySelector('#smallFontSize'),punctuationScale:document.querySelector('#punctuationScale'),fontFamily:document.querySelector('#fontFamily'),fontWeight:document.querySelector('#fontWeight'),letterSpacing:document.querySelector('#letterSpacing'),opacity:document.querySelector('#opacity'),stripSpaces:document.querySelector('#stripSpaces'),lineBreakColumn:document.querySelector('#lineBreakColumn'),pages:document.querySelector('#pages'),pageTemplate:document.querySelector('#pageTemplate'),pageCount:document.querySelector('#pageCount'),printBtn:document.querySelector('#printBtn'),copyLinkBtn:document.querySelector('#copyLinkBtn'),clearBtn:document.querySelector('#clearBtn'),templateName:document.querySelector('#templateName'),templateSelect:document.querySelector('#templateSelect'),saveTemplateBtn:document.querySelector('#saveTemplateBtn'),applyTemplateBtn:document.querySelector('#applyTemplateBtn'),deleteTemplateBtn:document.querySelector('#deleteTemplateBtn'),status:document.querySelector('#status')};
const stateKey='kanji-tracing-print', templateKey='kanji-tracing-templates';
const fonts={kyokasho:'"UD Digi Kyokasho N-R","UD デジタル 教科書体 N-R","BIZ UDPGothic","Yu Gothic",sans-serif',gothic:'"Yu Gothic","BIZ UDPGothic",sans-serif',mincho:'"Yu Mincho","BIZ UDPMincho",serif',maru:'"Yu Gothic","BIZ UDPGothic",sans-serif'};
function direction(){return document.querySelector('input[name="direction"]:checked')?.value||'ltr'}
function state(){return{sourceText:els.sourceText.value,studentName:els.studentName.value,worksheetDate:els.worksheetDate.value,cols:els.cols.value,rows:els.rows.value,fontSize:els.fontSize.value,smallFontSize:els.smallFontSize.value,punctuationScale:els.punctuationScale.value,fontFamily:els.fontFamily.value,fontWeight:els.fontWeight.value,letterSpacing:els.letterSpacing.value,opacity:els.opacity.value,stripSpaces:els.stripSpaces.checked,lineBreakColumn:els.lineBreakColumn.checked,direction:direction()}}
function apply(s){Object.entries(s||{}).forEach(([k,v])=>{if(k==='direction'){const r=document.querySelector(`input[name="direction"][value="${v}"]`);if(r)r.checked=true}else if(els[k]){if(typeof els[k].checked==='boolean')els[k].checked=!!v;else els[k].value=v}})}
function chars(){let text=els.sourceText.value;if(els.stripSpaces.checked)text=text.replace(/[ \t　]/g,'');const out=[];for(const ch of text){if(ch==='\r')continue;if(ch==='\n'){if(els.lineBreakColumn.checked)out.push('\n')}else out.push(ch)}return out}
function pagesFor(list,cols,rows){const per=cols*rows,pages=[[]];let colBreak=0;list.forEach(ch=>{if(ch==='\n'){colBreak=Math.ceil(pages.at(-1).length/rows)*rows;if(colBreak>=per){pages.push([]);colBreak=0}while(pages.at(-1).length<colBreak)pages.at(-1).push('');return}if(pages.at(-1).length>=per)pages.push([]);pages.at(-1).push(ch)});return pages}
function readingMarks(cols,dir){return Array.from({length:cols},(_,i)=>dir==='rtl'?cols-i:i+1)}
function render(){const cols=+els.cols.value||10,rows=+els.rows.value||14;document.documentElement.style.setProperty('--cell-w',`${198/cols}mm`);document.documentElement.style.setProperty('--cell-h',`${226.8/rows}mm`);document.documentElement.style.setProperty('--trace-opacity',String((+els.opacity.value||24)/100));document.documentElement.style.setProperty('--trace-size',`${els.fontSize.value}px`);document.documentElement.style.setProperty('--small-trace-size',`${els.smallFontSize.value}px`);document.documentElement.style.setProperty('--punctuation-size',`${Math.round((+els.fontSize.value||34)*(+els.punctuationScale.value||58)/100)}px`);document.documentElement.style.setProperty('--trace-font-family',fonts[els.fontFamily.value]||fonts.kyokasho);document.documentElement.style.setProperty('--trace-font-weight',els.fontWeight.value);document.documentElement.style.setProperty('--letter-spacing',`${els.letterSpacing.value}px`);const data=pagesFor(chars(),cols,rows);els.pages.replaceChildren();data.forEach((pageData,idx)=>{const page=els.pageTemplate.content.firstElementChild.cloneNode(true);page.querySelector('[data-name]').textContent=els.studentName.value;page.querySelector('[data-date]').textContent=els.worksheetDate.value;page.querySelector('[data-page-number]').textContent=`${idx+1} / ${data.length}`;const readings=page.querySelector('[data-readings]');readingMarks(cols,direction()).forEach(n=>{const d=document.createElement('div');d.textContent=n;readings.append(d)});const grid=page.querySelector('[data-grid]');grid.style.gridTemplateColumns=`repeat(${cols}, var(--cell-w))`;grid.style.gridTemplateRows=`repeat(${rows}, var(--cell-h))`;Array.from({length:cols*rows},(_,i)=>pageData[i]||'').forEach(ch=>{const c=document.createElement('div');c.className='cell';const t=document.createElement('span');t.className=/[、。，．]/.test(ch)?'punctuation':'trace';t.textContent=ch;c.append(t);grid.append(c)});els.pages.append(page)});els.pageCount.textContent=`${data.length}枚`;try{localStorage.setItem(stateKey,JSON.stringify(state()))}catch{}}
function templates(){try{return JSON.parse(localStorage.getItem(templateKey)||'{}')}catch{return{}}}function saveTemplates(t){localStorage.setItem(templateKey,JSON.stringify(t))}function refresh(selected=''){const t=templates(),names=Object.keys(t).sort((a,b)=>a.localeCompare(b,'ja'));els.templateSelect.textContent='';const e=document.createElement('option');e.value='';e.textContent=names.length?'選択してください':'保存されたテンプレートはありません';els.templateSelect.append(e);names.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;els.templateSelect.append(o)});if(selected)els.templateSelect.value=selected}
function setStatus(m){els.status.textContent=m;clearTimeout(window._st);window._st=setTimeout(()=>els.status.textContent='',2500)}
function encode(s){return btoa(unescape(encodeURIComponent(JSON.stringify(s))))}function decode(s){try{return JSON.parse(decodeURIComponent(escape(atob(s))))}catch{return null}}
function load(){const hash=location.hash.replace(/^#data=/,'');if(hash){const d=decode(hash);if(d)apply(d)}else{try{apply(JSON.parse(localStorage.getItem(stateKey)||'{}'))}catch{}}}
[els.sourceText,els.studentName,els.worksheetDate,els.cols,els.rows,els.fontSize,els.smallFontSize,els.punctuationScale,els.fontFamily,els.fontWeight,els.letterSpacing,els.opacity,els.stripSpaces,els.lineBreakColumn,...document.querySelectorAll('input[name="direction"]')].forEach(el=>el.addEventListener('input',render));
els.printBtn.addEventListener('click',()=>{render();window.print()});els.clearBtn.addEventListener('click',()=>{els.sourceText.value='';render()});els.copyLinkBtn.addEventListener('click',async()=>{const url=`${location.origin}${location.pathname}#data=${encode(state())}`;try{await navigator.clipboard.writeText(url);setStatus('共有URLをコピーしました。')}catch{location.hash=`data=${encode(state())}`;setStatus('URL欄に共有用データを入れました。')}});els.saveTemplateBtn.addEventListener('click',()=>{const n=els.templateName.value.trim();if(!n)return setStatus('保存名を入力してください。');const t=templates();t[n]=state();saveTemplates(t);refresh(n);setStatus('テンプレートを保存しました。')});els.applyTemplateBtn.addEventListener('click',()=>{const t=templates(),n=els.templateSelect.value;if(t[n]){apply(t[n]);render();setStatus('テンプレートを適用しました。')}});els.deleteTemplateBtn.addEventListener('click',()=>{const t=templates(),n=els.templateSelect.value;if(t[n]){delete t[n];saveTemplates(t);refresh();setStatus('テンプレートを削除しました。')}});
load();refresh();render();
