window.PRINT_RESOURCES = [
  ...(Array.isArray(window.PRINT_RESOURCES) ? window.PRINT_RESOURCES : []),
  {
    id: "surapuri-grade2-math-hub",
    title: "小学2年生 算数プリント一覧",
    description: "2年生の算数単元をまとめて探せます。スモールステップで単元数が多い入口です。",
    url: "https://surapuri.jp/elementary_school02/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "2年生まとめ",
    tags: ["2年生", "算数", "単元一覧", "特別支援", "スモールステップ"],
  },
  {
    id: "surapuri-multiplication99-grade2",
    title: "小学2年生 かけ算九九",
    description: "かけ算の意味から九九まで、段階的に練習できるプリントです。",
    url: "https://surapuri.jp/elementary_school02/multiplication99/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "かけ算九九",
    tags: ["2年生", "九九", "かけ算", "算数", "スモールステップ"],
  },
  {
    id: "surapuri-time-grade2",
    title: "小学2年生 時こくと時間",
    description: "時刻と時間の違い、何分後・何分前、時間と分の関係を練習できます。",
    url: "https://surapuri.jp/elementary_school02/time/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "時刻と時間",
    tags: ["2年生", "時計", "時刻", "時間", "何分後"],
  },
  {
    id: "surapuri-length-unit-grade2",
    title: "小学2年生 長さのたんい",
    description: "cm、mm、ものさし、単位なおし、長さ比べ、長さのたし算・ひき算を練習できます。",
    url: "https://surapuri.jp/elementary_school02/length/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "長さ",
    tags: ["2年生", "長さ", "cm", "mm", "ものさし"],
  },
  {
    id: "surapuri-length-meter-grade2",
    title: "小学2年生 長いものの長さ",
    description: "mとcmの単位変換、たし算・ひき算、長いものの長さを練習できます。",
    url: "https://surapuri.jp/elementary_school02/length2/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "長さ",
    tags: ["2年生", "m", "cm", "単位変換", "長いもの"],
  },
  {
    id: "surapuri-capacity-grade2",
    title: "小学2年生 水のかさ",
    description: "L、dL、mL、かさのたし算・ひき算を単元別に練習できます。",
    url: "https://surapuri.jp/elementary_school02/water-volume/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "水のかさ",
    tags: ["2年生", "水のかさ", "L", "dL", "mL"],
  },
  {
    id: "surapuri-shape-grade2",
    title: "小学2年生 長方形と正方形",
    description: "三角形・四角形、直角三角形、長方形、正方形を見つける練習ができます。",
    url: "https://surapuri.jp/elementary_school02/chouhouke-seihoukei-nama/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "図形",
    tags: ["2年生", "図形", "三角形", "四角形", "直角"],
  },
  {
    id: "surapuri-graph-grade2",
    title: "小学2年生 グラフとひょう",
    description: "表を作る、グラフで表す、表とグラフを読み取る練習ができます。",
    url: "https://surapuri.jp/elementary_school02/graph/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["2"],
    unit: "表とグラフ",
    tags: ["2年生", "表", "グラフ", "読み取り", "データ"],
  },
  {
    id: "sukiruma-time-grade2",
    title: "小学2年生 時こくと時間",
    description: "1時間=60分、午前・午後、1日=24時間などを含む時刻と時間のプリントです。",
    url: "https://sukiruma.net/download-san2_zikoku/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "時刻と時間",
    tags: ["2年生", "時計", "時刻", "時間", "午前午後"],
  },
  {
    id: "sukiruma-length-grade2",
    title: "小学2年生 長さのたんい",
    description: "cm、mmの読み方・書き方、ものさし、単位換算を練習できます。",
    url: "https://sukiruma.net/download-san2_nagasatani/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "長さ",
    tags: ["2年生", "長さ", "cm", "mm", "単位換算"],
  },
  {
    id: "sukiruma-capacity-grade2",
    title: "小学2年生 かさのたんい",
    description: "L、dL、mLの関係、かさの単位変換、たし算・ひき算を練習できます。",
    url: "https://sukiruma.net/download-san2_kasatani/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "水のかさ",
    tags: ["2年生", "水のかさ", "L", "dL", "mL"],
  },
  {
    id: "sukiruma-shape-grade2",
    title: "小学2年生 三角形と四角形",
    description: "三角形、四角形、長方形、正方形、直角三角形などを練習できます。",
    url: "https://sukiruma.net/download-san2_katati/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "図形",
    tags: ["2年生", "図形", "三角形", "四角形", "直角"],
  },
  {
    id: "sukiruma-addition-column-grade2",
    title: "小学2年生 たし算のひっさん",
    description: "位ごとに計算する筆算、くり上がりのあるたし算を練習できます。",
    url: "https://sukiruma.net/download-san2_tahissan/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "筆算",
    tags: ["2年生", "たし算", "筆算", "くり上がり", "計算"],
  },
  {
    id: "sukiruma-multiplication-grade2",
    title: "小学2年生 かけ算",
    description: "かけ算の意味、九九、1つ分の数といくつ分を考えるプリントです。",
    url: "https://sukiruma.net/download-san2_kakezan/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["2"],
    unit: "かけ算九九",
    tags: ["2年生", "かけ算", "九九", "文章題", "計算"],
  },
  {
    id: "sangan-length-meter-grade2",
    title: "小学2年生 長さ メートル",
    description: "m・cm・mm、単位つきのたし算・ひき算をPDFドリルで練習できます。",
    url: "https://www.sangan.jp/grade/m22-41.htm",
    siteId: "sangan",
    siteTitle: "算願",
    subject: "算数",
    grades: ["2"],
    unit: "長さ",
    tags: ["2年生", "長さ", "m", "cm", "mm"],
  },
];
