window.PRINT_RESOURCES = [
  ...(Array.isArray(window.PRINT_RESOURCES) ? window.PRINT_RESOURCES : []),
  {
    id: "surapuri-grade3-math-hub",
    title: "小学3年生 算数プリント一覧",
    description: "小数、分数、図形、重さ、時こくと時間、わり算、表とぼうグラフなどを単元別に探せます。",
    url: "https://surapuri.jp/elementary_school03/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["3"],
    unit: "3年生まとめ",
    tags: ["3年生", "算数", "単元一覧", "特別支援", "スモールステップ"],
  },
  {
    id: "surapuri-division-grade3",
    title: "小学3年生 わり算",
    description: "同じ数ずつ分ける導入から、九九を使ったわり算まで段階的に練習できます。",
    url: "https://surapuri.jp/elementary_school03/division/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["3"],
    unit: "わり算",
    tags: ["3年生", "わり算", "九九", "算数", "スモールステップ"],
  },
  {
    id: "surapuri-fraction-grade3",
    title: "小学3年生 分数とは",
    description: "分数の読み方、分母と分子、数直線、分数のたし算・ひき算の入口を練習できます。",
    url: "https://surapuri.jp/elementary_school03/fraction/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["3"],
    unit: "分数",
    tags: ["3年生", "分数", "数直線", "たし算", "ひき算"],
  },
  {
    id: "surapuri-big-number-grade3",
    title: "小学3年生 大きい数のしくみ",
    description: "一万、十万、百万、千万までの数の読み書きや数直線を練習できます。",
    url: "https://surapuri.jp/elementary_school03/big-number/",
    siteId: "surapuri",
    siteTitle: "すらぷり",
    subject: "算数",
    grades: ["3"],
    unit: "大きい数",
    tags: ["3年生", "大きい数", "位", "数直線", "算数"],
  },
  {
    id: "sukiruma-grade3-math-hub",
    title: "小学3年生 算数ワーク",
    description: "かけ算とわり算、円と球、小数、分数、重さ、三角形と角、表とぼうグラフなどを一覧で探せます。",
    url: "https://sukiruma.net/work-san3nen/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["3"],
    unit: "3年生まとめ",
    tags: ["3年生", "算数", "単元一覧", "無料", "ワーク"],
  },
  {
    id: "sukiruma-time-grade3",
    title: "小学3年生 時こくと時間",
    description: "午前・午後、正午、何分後・何分前、時間・分・秒を使う問題を練習できます。",
    url: "https://sukiruma.net/download-san3_3zikoku/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["3"],
    unit: "時こくと時間",
    tags: ["3年生", "時計", "時こく", "時間", "午前午後"],
  },
  {
    id: "sukiruma-decimal-grade3",
    title: "小学3年生 小数のしくみ",
    description: "小数の読み方、整数部分と小数部分、かさや長さでの小数の表し方を練習できます。",
    url: "https://sukiruma.net/download-san3_syousu/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["3"],
    unit: "小数",
    tags: ["3年生", "小数", "数", "長さ", "かさ"],
  },
  {
    id: "sukiruma-weight-grade3",
    title: "小学3年生 重さの単位",
    description: "g、kgなどの重さの単位、はかりの目盛り、重さ比べを練習できます。",
    url: "https://sukiruma.net/download-san3_omosa/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["3"],
    unit: "重さ",
    tags: ["3年生", "重さ", "g", "kg", "はかり"],
  },
  {
    id: "sukiruma-bar-graph-grade3",
    title: "小学3年生 表とぼうグラフ",
    description: "資料を整理して表にまとめる、棒グラフを読む・かく練習ができます。",
    url: "https://sukiruma.net/download-san3_3gurahu/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["3"],
    unit: "表とぼうグラフ",
    tags: ["3年生", "表", "ぼうグラフ", "データ", "算数"],
  },
  {
    id: "chibimusu-kanji-grade3",
    title: "小学3年生 漢字練習・テスト",
    description: "3年生で習う200字の漢字練習、書き取りテスト、漢字ポスター、漢字カードを探せます。",
    url: "https://happylilac.net/sy-kanzi3h",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["3"],
    unit: "漢字",
    tags: ["3年生", "漢字", "書き取り", "テスト", "ポスター"],
  },
];
