window.RESOURCE_LINKS = [
  {
    id: "surapuri",
    title: "すらぷり",
    description: "発達障害や学習につまずきがある子向けに、スモールステップの算数プリントを探せます。",
    url: "https://surapuri.jp/",
    subjects: ["算数"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["特別支援", "スモールステップ", "無料", "PDF"],
    note: "発達障害対応を前面に出しているプリントサイトです。",
  },
  {
    id: "chibimusu",
    title: "ちびむすドリル",
    description: "幼児から小学生、中学生までの学習プリントを幅広く探せます。",
    url: "https://happylilac.net/",
    subjects: ["算数", "国語", "社会", "英語", "その他"],
    grades: ["pre", "1", "2", "3", "4", "5", "6"],
    tags: ["無料", "幅広い", "漢字", "時計", "白地図"],
    note: "プリントの量が多いので、教科や学年の入口から探すと使いやすいです。",
  },
  {
    id: "print-kids",
    title: "ぷりんときっず",
    description: "幼児から小学3年生までの国語・算数プリントを、学年や見本画像から探せます。",
    url: "https://print-kids.net/",
    subjects: ["算数", "国語", "その他"],
    grades: ["pre", "1", "2", "3"],
    tags: ["無料", "低学年", "時計", "なぞり", "見本画像"],
    note: "低学年中心で、見本を見ながら教材を選びやすいサイトです。",
  },
  {
    id: "sukiruma",
    title: "すきるまドリル",
    description: "小学校1年生から6年生までの算数ワーク、計算ドリル、漢字ワークを探せます。",
    url: "https://sukiruma.net/",
    subjects: ["算数", "国語", "英語", "その他"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["無料", "単元別", "計算", "漢字", "英語"],
    note: "単元別の予習・復習プリントを探す入口に向いています。",
  },
  {
    id: "tsukupri",
    title: "つくプリ",
    description: "入力した文字から、ひらがな・漢字・ローマ字・算数の練習プリントを作れます。",
    url: "https://tsukupri.jp/",
    subjects: ["国語", "算数"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["作成ツール", "なぞり", "漢字", "ローマ字", "無料"],
    note: "児童名や住所など、個別の文字練習を作りたいときに便利です。",
  },
  {
    id: "sangan",
    title: "算願",
    description: "算数・計算PDFプリントを、学年別・単元別に探せます。",
    url: "https://www.sangan.jp/",
    subjects: ["算数"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["算数", "計算", "PDF", "大量", "無料"],
    note: "計算練習の量を確保したいときに向いています。利用範囲はサイト側の案内を確認してください。",
  },
  {
    id: "jakka",
    title: "JAKKA",
    description: "漢字・国語・ひらがな・カタカナなどのPDFプリントを探せます。",
    url: "https://www.jakka.jp/",
    subjects: ["国語"],
    grades: ["pre", "1", "2", "3", "4", "5", "6"],
    tags: ["漢字", "国語", "ひらがな", "カタカナ", "PDF"],
    note: "文字練習や漢字ドリルの補助教材を探す入口に使えます。",
  },
  {
    id: "mugen-print",
    title: "むげんプリント",
    description: "小学1年生から6年生の算数・国語プリントを探せます。",
    url: "https://mugen-print.com/",
    subjects: ["算数", "国語"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["無料", "国語", "算数", "ランダム"],
    note: "ダウンロードするたびに内容が変わる形式のプリントがあります。",
  },
  {
    id: "okadori",
    title: "おかわりドリル",
    description: "小学生・中学生向けの問題プリントと学習コンテンツを探せます。",
    url: "https://www.okadori.net/",
    subjects: ["算数", "国語", "理科", "社会", "その他"],
    grades: ["1", "2", "3", "4", "5", "6"],
    tags: ["無料", "解説", "PDF", "学年別"],
    note: "問題と答えのセットを探したいときに向いています。",
  },
  {
    id: "plus-print",
    title: "ぷらすプリント",
    description: "幼児・小学生向けのプリントを、入学準備や教科別に探せます。",
    url: "https://plus-print.com/",
    subjects: ["算数", "国語", "社会", "その他"],
    grades: ["pre", "1", "2", "3", "4", "5", "6"],
    tags: ["無料", "入学準備", "低学年", "都道府県"],
    note: "新しい教材も追加されているため、低学年や入学準備の入口に使えます。",
  },
];

window.PRINT_RESOURCES = [
  {
    id: "print-kids-clock-read",
    title: "時計の読み方 練習プリント",
    description: "時計を読んで時刻を書く練習。難易度、答えあり・なし、補助数字つきの形式を選べます。",
    url: "https://print-kids.net/print/sansuu/tokei/",
    siteId: "print-kids",
    siteTitle: "ぷりんときっず",
    subject: "算数",
    grades: ["1", "2"],
    unit: "時計",
    tags: ["時計", "時刻", "補助数字", "答えあり", "低学年"],
  },
  {
    id: "print-kids-clock-draw",
    title: "時計の書き方 練習プリント",
    description: "示された時刻になるように、時計の針を書き込む練習プリントです。",
    url: "https://print-kids.net/print/sansuu/tokei-kakikata/",
    siteId: "print-kids",
    siteTitle: "ぷりんときっず",
    subject: "算数",
    grades: ["1", "2"],
    unit: "時計",
    tags: ["時計", "針を書く", "補助あり", "答えあり"],
  },
  {
    id: "chibimusu-clock-youji",
    title: "時計の読み方 練習プリント",
    description: "導入編、練習編、マスター編、針を書きこむプリントなどを選べます。",
    url: "https://happylilac.net/tokei.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["pre", "1", "2"],
    unit: "時計",
    tags: ["時計", "導入", "補助数字", "針を書く", "無料"],
  },
  {
    id: "chibimusu-clock-time",
    title: "時計 / 時刻と時間",
    description: "小学生向けの時計、時刻と時間の問題プリントを探せます。",
    url: "https://happylilac.net/p-zikan.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["2", "3"],
    unit: "時刻と時間",
    tags: ["時計", "時刻", "時間", "何分後", "何分前"],
  },
  {
    id: "chibimusu-clock-poster",
    title: "時計の読みかた 学習ポスター",
    description: "時計の読み方を確認できるポスター。支援用の掲示や導入に使いやすい教材です。",
    url: "https://happylilac.net/tokei-hyo.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "算数",
    grades: ["pre", "1", "2"],
    unit: "時計",
    tags: ["時計", "ポスター", "補助", "導入"],
  },
  {
    id: "sukiruma-number-count",
    title: "小学1年生 算数 いくつあるかな",
    description: "数を数えて数字を書く練習。数の大きさを比べる練習にもつながります。",
    url: "https://sukiruma.net/download-san1_ikutu/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["1"],
    unit: "かず",
    tags: ["かず", "数える", "1年生", "算数ワーク"],
  },
  {
    id: "sukiruma-capacity-compare",
    title: "小学1年生 算数 かさくらべ",
    description: "水のかさを直接比較、間接比較で比べる学習プリントです。",
    url: "https://sukiruma.net/download-san1_kasa/",
    siteId: "sukiruma",
    siteTitle: "すきるまドリル",
    subject: "算数",
    grades: ["1"],
    unit: "水のかさ",
    tags: ["かさ", "比較", "水", "1年生"],
  },
  {
    id: "chibimusu-kanji-grade1-number",
    title: "小学1年生 漢字練習 数",
    description: "一、二、三、十、百、千など、数に関する1年生漢字を練習できます。",
    url: "https://happylilac.net/sy-kanzi10.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["1"],
    unit: "漢字",
    tags: ["漢字", "1年生", "数", "なぞり"],
  },
  {
    id: "chibimusu-kanji-grade1-week",
    title: "小学1年生 漢字練習 曜日",
    description: "日、月、火、水、木、金、土など、曜日の漢字を練習できます。",
    url: "https://happylilac.net/sy-kanzi1.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["1"],
    unit: "漢字",
    tags: ["漢字", "1年生", "曜日", "なぞり"],
  },
  {
    id: "chibimusu-kanji-grade1-body",
    title: "小学1年生 漢字練習 人と体",
    description: "口、人、手、目、耳、足など、体や人に関する1年生漢字を練習できます。",
    url: "https://happylilac.net/sy-kanzi16.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["1"],
    unit: "漢字",
    tags: ["漢字", "1年生", "体", "なぞり"],
  },
  {
    id: "chibimusu-kanji-grade1-action",
    title: "小学1年生 漢字練習 動作",
    description: "見、立、休、入、出など、動作に関する1年生漢字を練習できます。",
    url: "https://happylilac.net/sy-kanzi15.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["1"],
    unit: "漢字",
    tags: ["漢字", "1年生", "動作", "なぞり"],
  },
  {
    id: "chibimusu-kanji-grade1-state",
    title: "小学1年生 漢字練習 様子",
    description: "大、中、小、上、下、右、左、白、青、赤などを練習できます。",
    url: "https://happylilac.net/sy-kanzi13.html",
    siteId: "chibimusu",
    siteTitle: "ちびむすドリル",
    subject: "国語",
    grades: ["1"],
    unit: "漢字",
    tags: ["漢字", "1年生", "様子", "色", "位置"],
  },
];
